// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Desktop.UI")>]
[<assembly: AssemblyProductAttribute("FSharp.Desktop.UI")>]
[<assembly: AssemblyDescriptionAttribute("F# MVC for WPF.")>]
[<assembly: AssemblyVersionAttribute("0.7.1")>]
[<assembly: AssemblyFileVersionAttribute("0.7.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Desktop.UI"
    let [<Literal>] AssemblyProduct = "FSharp.Desktop.UI"
    let [<Literal>] AssemblyDescription = "F# MVC for WPF."
    let [<Literal>] AssemblyVersion = "0.7.1"
    let [<Literal>] AssemblyFileVersion = "0.7.1"
